# Estimating computing times

In [23]:
import pandas as pd
import numpy as np

In [3]:
from fireworks import Firework, Workflow
from fireworks.utilities.filepad import FilePad

In [4]:
fp = FilePad(
    host='localhost',port=27018, database='fireworks-jhoermann',
    username='fireworks',password='fireworks')

In [6]:
content, doc = fp.get_file(identifier='surfactant_on_AU_111_df_json')

In [7]:
sim_df = pd.read_json(content, orient='index')

In [8]:
len(sim_df)

228

In [9]:
preassemblies_of_interest = {
    'cylinders_with_counterion',
    'hemicylinders_with_counterion',
    'bilayer_with_counterion',
    'monolayer_with_counterion'}

## Filter unique crystal planes

In [90]:
unique_crystal_planes = sim_df["sb_crystal_plane"].unique()

In [91]:
unique_crystal_planes

array([111])

### Filter unique substrate measures and box measures
(for SDS systems)

In [146]:
# original SDS systems without indenter
system_name_scope = list( sim_df[ 
        sim_df['indenter'].isna() & \
        (sim_df['surfactant'] == 'SDS') &
        sim_df['sf_preassembly'].isin(preassemblies_of_interest)
    ].index )

In [147]:
unique_sb_multiples = np.unique(
   np.vstack( sim_df[
       sim_df["sb_crystal_plane"] == unique_crystal_planes[0]
   ].loc[system_name_scope][["sb_multiples"]].values.flatten() ), axis=0 )

In [148]:
unique_sb_multiples

array([[17, 10,  2],
       [26, 15,  2],
       [51, 30,  2],
       [60, 35,  2]])

In [149]:
unique_sb_names = sim_df.loc[system_name_scope]['sb_name'].unique()

In [150]:
unique_sb_names

array(['AU_111_60x35x2', 'AU_111_51x30x2', 'AU_111_17x10x2',
       'AU_111_26x15x2'], dtype=object)

In [151]:
unique_boxes = np.unique(
   np.vstack( sim_df[
       sim_df["sb_crystal_plane"] == unique_crystal_planes[0]
   ].loc[system_name_scope]["box"].values.flatten() ), axis=0 )

In [152]:
unique_boxes

array([[4.90e-09, 5.00e-09, 1.80e-08],
       [7.50e-09, 7.50e-09, 1.80e-08],
       [1.47e-08, 1.50e-08, 1.80e-08],
       [1.73e-08, 1.75e-08, 1.80e-08]])

In [153]:
systems_of_interest_SDS = list( 
    sim_df.loc[system_name_scope][
        sim_df.loc[system_name_scope,'sb_name'] == unique_sb_names[1]
    ].index )

In [154]:
systems_of_interest_SDS

['1107_SDS_on_AU_111_51x30x2_bilayer_with_counterion',
 '1107_SDS_on_AU_111_51x30x2_cylinders_with_counterion',
 '1107_SDS_on_AU_111_51x30x2_hemicylinders_with_counterion',
 '1107_SDS_on_AU_111_51x30x2_monolayer_with_counterion',
 '129_SDS_on_AU_111_51x30x2_bilayer_with_counterion',
 '129_SDS_on_AU_111_51x30x2_cylinders_with_counterion',
 '129_SDS_on_AU_111_51x30x2_hemicylinders_with_counterion',
 '129_SDS_on_AU_111_51x30x2_monolayer_with_counterion',
 '220_SDS_on_AU_111_51x30x2_bilayer_with_counterion',
 '220_SDS_on_AU_111_51x30x2_cylinders_with_counterion',
 '220_SDS_on_AU_111_51x30x2_hemicylinders_with_counterion',
 '220_SDS_on_AU_111_51x30x2_monolayer_with_counterion',
 '2214_SDS_on_AU_111_51x30x2_bilayer_with_counterion',
 '2214_SDS_on_AU_111_51x30x2_cylinders_with_counterion',
 '2214_SDS_on_AU_111_51x30x2_hemicylinders_with_counterion',
 '2214_SDS_on_AU_111_51x30x2_monolayer_with_counterion',
 '377_SDS_on_AU_111_51x30x2_bilayer_with_counterion',
 '377_SDS_on_AU_111_51x30x2_cylind

In [604]:
len(systems_of_interest_SDS)

28

In [155]:
box_measures_SDS_SI = np.unique(
   np.vstack( sim_df.loc[systems_of_interest_SDS]["box"].values.flatten() ), axis=0 )

In [166]:
box_measures_SDS_SI * 1e9 # nm

array([[14.7, 15. , 18. ]])

In [158]:
box_volume_SDS_SI = np.product( box_measures_SDS_SI )

In [159]:
round(box_volume_SDS_SI * 1e27) # nm cube

3969.0

### Filtering CTAB

In [92]:
# original CTAB systems without indenter
system_name_scope = list( sim_df[ 
        sim_df['indenter'].isna() & \
        (sim_df['surfactant'] == 'CTAB') &
        sim_df['sf_preassembly'].isin(preassemblies_of_interest)
    ].index )

In [93]:
unique_sb_multiples = np.unique(
   np.vstack( sim_df[
       sim_df["sb_crystal_plane"] == unique_crystal_planes[0]
   ].loc[system_name_scope][["sb_multiples"]].values.flatten() ), axis=0 )

In [94]:
unique_sb_multiples

array([[21, 12,  2],
       [30, 18,  2],
       [63, 36,  2],
       [72, 42,  2]])

In [95]:
unique_sb_names = sim_df.loc[system_name_scope]['sb_name'].unique()

In [96]:
unique_sb_names

array(['AU_111_63x36x2', 'AU_111_21x12x2', 'AU_111_30x18x2',
       'AU_111_72x42x2'], dtype=object)

In [97]:
unique_boxes = np.unique(
   np.vstack( sim_df[
       sim_df["sb_crystal_plane"] == unique_crystal_planes[0]
   ].loc[system_name_scope]["box"].values.flatten() ), axis=0 )

In [98]:
unique_boxes

array([[6.10e-09, 6.00e-09, 1.80e-08],
       [8.70e-09, 9.00e-09, 1.80e-08],
       [1.82e-08, 1.80e-08, 1.80e-08],
       [2.08e-08, 2.10e-08, 1.80e-08]])

In [101]:
systems_of_interest_CTAB = list( sim_df.loc[system_name_scope][
    sim_df.loc[system_name_scope,'sb_name'] == unique_sb_names[0]].index )

In [116]:
systems_of_interest_CTAB

['1010_CTAB_on_AU_111_63x36x2_bilayer_with_counterion',
 '1010_CTAB_on_AU_111_63x36x2_cylinders_with_counterion',
 '1010_CTAB_on_AU_111_63x36x2_hemicylinders_with_counterion',
 '1010_CTAB_on_AU_111_63x36x2_monolayer_with_counterion',
 '1298_CTAB_on_AU_111_63x36x2_bilayer_with_counterion',
 '1298_CTAB_on_AU_111_63x36x2_cylinders_with_counterion',
 '1298_CTAB_on_AU_111_63x36x2_hemicylinders_with_counterion',
 '1298_CTAB_on_AU_111_63x36x2_monolayer_with_counterion',
 '367_CTAB_on_AU_111_63x36x2_bilayer_with_counterion',
 '367_CTAB_on_AU_111_63x36x2_cylinders_with_counterion',
 '367_CTAB_on_AU_111_63x36x2_hemicylinders_with_counterion',
 '367_CTAB_on_AU_111_63x36x2_monolayer_with_counterion',
 '415_CTAB_on_AU_111_63x36x2_bilayer_with_counterion',
 '415_CTAB_on_AU_111_63x36x2_cylinders_with_counterion',
 '415_CTAB_on_AU_111_63x36x2_hemicylinders_with_counterion',
 '415_CTAB_on_AU_111_63x36x2_monolayer_with_counterion',
 '515_CTAB_on_AU_111_63x36x2_bilayer_with_counterion',
 '515_CTAB_on_AU_

In [603]:
len(systems_of_interest_CTAB)

24

In [137]:
box_measures_CTAB_SI = np.unique(
   np.vstack( sim_df.loc[systems_of_interest_CTAB]["box"].values.flatten() ), axis=0 )

In [165]:
box_measures_CTAB_SI * 1e9 # nm

array([[18.2, 18. , 18. ]])

In [160]:
box_volume_CTAB_SI = np.product( box_measures_CTAB_SI )

In [161]:
round(box_volume_CTAB_SI * 1e27) # nm cube

5897.0

### Reference particle number estimate

In [117]:
solvent_molecules_per_nm_cube = 33 # corresponds to standard conditions, 0.99 kg / L

In [122]:
number_of_atoms_in_solvent_molecule = 3 #water

In [128]:
particle_density_SI = number_of_atoms_in_solvent_molecule * solvent_molecules_per_nm_cube * 1e27 # per m^-3

In [129]:
particle_density_SI 

9.900000000000001e+28

In [163]:
reference_number_of_particles_SDS = round(
    particle_density_SI * box_volume_SDS_SI)

In [143]:
reference_number_of_particles_CTAB = round(
    particle_density_SI * box_volume_CTAB_SI)

In [164]:
reference_number_of_particles_SDS

392931.0

In [144]:
reference_number_of_particles_CTAB

583783.0

In [306]:
i = 1
while(reference_number_of_particles_SDS / 10**i > 9 ): 
    i = i+1
reference_number_of_particles_SDS_rounded = round(
    reference_number_of_particles_SDS, -i)

In [307]:
i = 1
while(reference_number_of_particles_CTAB / 10**i > 9 ): 
    i = i+1
reference_number_of_particles_CTAB_rounded = round(
    reference_number_of_particles_CTAB, -i)

In [309]:
reference_number_of_particles_SDS_rounded

400000.0

In [310]:
reference_number_of_particles_CTAB_rounded

600000.0

### AFM approach time span estimate

In [500]:
box_measures_CTAB_SI * 1e9

array([[18.2, 18. , 18. ]])

In [501]:
d = 7.5 # intital distance (nm) from tip apex to surface (better be more than that)

In [502]:
dt = 2 # fs per timestep

In [503]:
d_SI = d*1e-9

In [504]:
d_SI # apex - substrate distance in m

7.500000000000001e-09

In [505]:
dt_SI = dt*1e-15

In [506]:
dt_SI # seconds per timestep

2e-15

In [507]:
v_SI = np.array([1, 0.1, 0.01, 0.001]) # m / s, dm /s , cm / s, mm / s

In [508]:
v_SI # m / s = nm / ns

array([1.   , 0.1  , 0.01 , 0.001])

In [509]:
t_ns = d / v_SI # simulation time span in ns

In [510]:
t_ns

array([   7.5,   75. ,  750. , 7500. ])

In [511]:
v_SI

array([1.   , 0.1  , 0.01 , 0.001])

In [512]:
necessary_steps = d_SI / (v_SI * dt_SI)

In [513]:
np.round(necessary_steps)/1e9

array([0.00375, 0.0375 , 0.375  , 3.75   ])

In [514]:
necessary_steps[2] # at 1 cm / s

375000000.0

### core h estimate

In [515]:
core_h_per_particle_ns = 0.3e-3 # based on hfr13 2018 JURECA benchmark

In [516]:
core_h_estimate_for_AFM_probe_of_SDS = \
    core_h_per_particle_ns * reference_number_of_particles_SDS_rounded * t_ns

In [517]:
core_h_estimate_for_AFM_probe_of_SDS

array([   900.,   9000.,  90000., 900000.])

In [518]:
core_h_estimate_for_AFM_probe_of_CTAB = \
    core_h_per_particle_ns * reference_number_of_particles_CTAB_rounded * t_ns

In [529]:
core_h_estimate_for_AFM_probe_of_CTAB

array([   1350.,   13500.,  135000., 1350000.])

In [530]:
core_h_per_particle_ns

0.0003

### number of cores estimate

In [531]:
particles_per_core = 2500 # based on hfr13 2018 JURECA benchmark

In [532]:
no_of_cores_for_SDS = reference_number_of_particles_SDS_rounded / particles_per_core

In [533]:
no_of_cores_for_SDS

160.0

In [534]:
cores_per_node = 48 # JUWELS

In [535]:
no_of_cores_for_SDS / cores_per_node # nodes

3.3333333333333335

In [536]:
no_of_cores_for_SDS_rounded = cores_per_node * \
    np.ceil(no_of_cores_for_SDS / cores_per_node) # nodes

In [537]:
no_of_cores_for_SDS_rounded

192.0

In [538]:
# wall time per step [hours]
core_h_estimate_for_AFM_probe_of_SDS \
    / no_of_cores_for_SDS_rounded / necessary_steps

array([1.25e-06, 1.25e-06, 1.25e-06, 1.25e-06])

In [539]:
# wall time per step [hours]
wall_time_per_step_SDS = (core_h_estimate_for_AFM_probe_of_SDS \
    / no_of_cores_for_SDS_rounded / necessary_steps)[0]

In [540]:
wall_time_per_step_SDS

1.2499999999999997e-06

In [541]:
no_of_cores_for_CTAB = reference_number_of_particles_CTAB_rounded / particles_per_core

In [542]:
no_of_cores_for_CTAB

240.0

In [543]:
no_of_cores_for_CTAB / 48 # nodes

5.0

In [544]:
no_of_cores_for_CTAB_rounded = no_of_cores_for_CTAB # geht schön auf

In [545]:
# wall time per step [hours]
core_h_estimate_for_AFM_probe_of_CTAB \
    / no_of_cores_for_CTAB / necessary_steps

array([1.5e-06, 1.5e-06, 1.5e-06, 1.5e-06])

In [546]:
# wall time per step [hours]
wall_time_per_step_CTAB = (core_h_estimate_for_AFM_probe_of_CTAB \
    / no_of_cores_for_CTAB / necessary_steps)[0]

In [547]:
wall_time_per_step_CTAB

1.4999999999999998e-06

In [548]:
necessary_steps

array([3.75e+06, 3.75e+07, 3.75e+08, 3.75e+09])

In [549]:
core_h_estimate_for_AFM_probe_of_SDS_check = \
    necessary_steps*wall_time_per_step_SDS*no_of_cores_for_SDS_rounded

In [550]:
core_h_estimate_for_AFM_probe_of_SDS

array([   900.,   9000.,  90000., 900000.])

In [551]:
core_h_estimate_for_AFM_probe_of_SDS_check

array([   900.,   9000.,  90000., 900000.])

In [552]:
core_h_estimate_for_AFM_probe_of_CTAB_check = \
    necessary_steps*wall_time_per_step_CTAB*no_of_cores_for_CTAB_rounded

In [553]:
core_h_estimate_for_AFM_probe_of_CTAB

array([   1350.,   13500.,  135000., 1350000.])

In [554]:
core_h_estimate_for_AFM_probe_of_CTAB_check

array([   1350.,   13500.,  135000., 1350000.])

# Shear MD

### SDS

In [476]:
round(box_measures_SDS_SI[0,1]*1e9)# lateral box measures

15.0

In [477]:
d_SDS = no_of_transitions * round(box_measures_SDS_SI[0,1]*1e9)

In [478]:
d_SDS

45.0

In [479]:
v_SI

array([1.   , 0.1  , 0.01 , 0.001])

In [480]:
d_SDS_SI = d_SDS * 1e-9

In [481]:
necessary_steps_SDS = d_SDS_SI / (v_SI * dt_SI)

In [482]:
necessary_steps_SDS

array([2.25e+07, 2.25e+08, 2.25e+09, 2.25e+10])

In [473]:
necessary_steps_CTAB[1] # at 1 cm / s

270000000.0

In [483]:
necessary_steps_SDS[1] * 1e-9

0.225

In [485]:
t_SDS_ns = d_SDS / v_SI # simulation time span in ns

In [488]:
t_SDS_ns

array([   45.,   450.,  4500., 45000.])

### CTAB

In [434]:
no_of_transitions = 3

In [442]:
round(box_measures_CTAB_SI[0,1]*1e9)# lateral box measures

18.0

In [460]:
d_CTAB = no_of_transitions * round(box_measures_CTAB_SI[0,1]*1e9)

In [602]:
d_CTAB

54.0

In [461]:
v_SI

array([1.   , 0.1  , 0.01 , 0.001])

In [465]:
d_CTAB_SI = d_CTAB * 1e-9

In [470]:
necessary_steps_CTAB = d_CTAB_SI / (v_SI * dt_SI)

In [472]:
necessary_steps_CTAB

array([2.7e+07, 2.7e+08, 2.7e+09, 2.7e+10])

In [473]:
necessary_steps_CTAB[1] # at 1 cm / s

270000000.0

In [474]:
necessary_steps_CTAB[1] * 1e-9

0.27

In [490]:
t_CTAB_ns = d_CTAB / v_SI # simulation time span in ns

In [491]:
t_CTAB_ns

array([   54.,   540.,  5400., 54000.])

### core h estimate

In [484]:
core_h_per_particle_ns = 0.3e-3 # based on hfr13 2018 JURECA benchmark

In [494]:
core_h_estimate_for_shear_of_SDS = core_h_per_particle_ns \
    * reference_number_of_particles_SDS_rounded * t_SDS_ns

In [496]:
core_h_estimate_for_shear_of_SDS

array([   5400.,   54000.,  540000., 5400000.])

In [497]:
core_h_estimate_for_shear_of_CTAB = core_h_per_particle_ns \
    * reference_number_of_particles_CTAB_rounded * t_CTAB_ns

In [499]:
core_h_estimate_for_shear_of_CTAB

array([   9720.,   97200.,  972000., 9720000.])

### number of cores estimate

In [565]:
particles_per_core = 2500 # based on hfr13 2018 JURECA benchmark

In [566]:
no_of_cores_for_SDS = \
    reference_number_of_particles_SDS_rounded / particles_per_core

In [567]:
no_of_cores_for_SDS

160.0

In [568]:
cores_per_node = 48 # JUWELS

In [569]:
no_of_cores_for_SDS / cores_per_node # nodes

3.3333333333333335

In [570]:
no_of_cores_for_SDS_rounded = cores_per_node * \
    np.ceil(no_of_cores_for_SDS / cores_per_node) # nodes

In [571]:
no_of_cores_for_SDS_rounded

192.0

In [572]:
# wall time per step [hours]
core_h_estimate_for_shear_of_SDS \
    / no_of_cores_for_SDS_rounded / necessary_steps_SDS

array([1.25e-06, 1.25e-06, 1.25e-06, 1.25e-06])

In [573]:
# wall time per step [hours]
wall_time_per_step_SDS = (core_h_estimate_for_shear_of_SDS \
    / no_of_cores_for_SDS_rounded / necessary_steps_SDS)[0]

In [574]:
wall_time_per_step_SDS

1.2499999999999999e-06

In [575]:
no_of_cores_for_CTAB = \
    reference_number_of_particles_CTAB_rounded / particles_per_core

In [576]:
no_of_cores_for_CTAB

240.0

In [577]:
no_of_cores_for_CTAB / 48 # nodes

5.0

In [578]:
no_of_cores_for_CTAB_rounded = no_of_cores_for_CTAB # geht schön auf

In [579]:
# wall time per step [hours]
core_h_estimate_for_shear_of_CTAB \
    / no_of_cores_for_CTAB / necessary_steps_CTAB

array([1.5e-06, 1.5e-06, 1.5e-06, 1.5e-06])

In [582]:
# wall time per step [hours]
wall_time_per_step_CTAB = (core_h_estimate_for_shear_of_CTAB \
    / no_of_cores_for_CTAB / necessary_steps_CTAB)[0]

In [583]:
wall_time_per_step_CTAB

1.5e-06

In [365]:
necessary_steps

array([3.75e+06, 3.75e+07, 3.75e+08, 3.75e+09])

In [584]:
core_h_estimate_for_shear_of_SDS_check = \
    necessary_steps_SDS*wall_time_per_step_SDS*no_of_cores_for_SDS_rounded

In [587]:
core_h_estimate_for_shear_of_SDS

array([   5400.,   54000.,  540000., 5400000.])

In [588]:
core_h_estimate_for_shear_of_SDS_check

array([   5400.,   54000.,  540000., 5400000.])

In [589]:
core_h_estimate_for_shear_of_CTAB_check = \
    necessary_steps_CTAB*wall_time_per_step_CTAB*no_of_cores_for_CTAB_rounded

In [591]:
core_h_estimate_for_shear_of_CTAB

array([   9720.,   97200.,  972000., 9720000.])

In [590]:
core_h_estimate_for_shear_of_CTAB_check

array([9.72e+03, 9.72e+04, 9.72e+05, 9.72e+06])

In [593]:
(core_h_estimate_for_shear_of_SDS + core_h_estimate_for_shear_of_CTAB)*1.2

array([   18144.,   181440.,  1814400., 18144000.])

In [599]:
(core_h_estimate_for_AFM_probe_of_SDS + core_h_estimate_for_AFM_probe_of_CTAB)*2.4

array([   5400.,   54000.,  540000., 5400000.])

In [598]:
5.5*0.2

1.1

In [600]:
5400000 + 1814400

7214400

In [601]:
1.8+2.7+1.1+0.54+0.97+0.3

7.409999999999999

In [605]:
reference_number_of_particles_SDS_rounded

400000.0

## Previous

In [618]:
system_name_scope

['103_SDS_on_AU_111_60x35x2_bilayer_with_counterion',
 '1107_SDS_on_AU_111_51x30x2_bilayer_with_counterion',
 '1107_SDS_on_AU_111_51x30x2_cylinders_with_counterion',
 '1107_SDS_on_AU_111_51x30x2_hemicylinders_with_counterion',
 '1107_SDS_on_AU_111_51x30x2_monolayer_with_counterion',
 '123_SDS_on_AU_111_17x10x2_bilayer_with_counterion',
 '129_SDS_on_AU_111_51x30x2_bilayer_with_counterion',
 '129_SDS_on_AU_111_51x30x2_cylinders_with_counterion',
 '129_SDS_on_AU_111_51x30x2_hemicylinders_with_counterion',
 '129_SDS_on_AU_111_51x30x2_monolayer_with_counterion',
 '14_SDS_on_AU_111_17x10x2_bilayer_with_counterion',
 '1519_SDS_on_AU_111_60x35x2_bilayer_with_counterion',
 '165_SDS_on_AU_111_26x15x2_bilayer_with_counterion',
 '177_SDS_on_AU_111_60x35x2_bilayer_with_counterion',
 '19_SDS_on_AU_111_26x15x2_bilayer_with_counterion',
 '220_SDS_on_AU_111_51x30x2_bilayer_with_counterion',
 '220_SDS_on_AU_111_51x30x2_cylinders_with_counterion',
 '220_SDS_on_AU_111_51x30x2_hemicylinders_with_counterion

In [644]:
core_h_per_particle_ns * reference_number_of_particles_SDS_rounded *2 * 19

4559.999999999999

In [624]:
core_h_per_particle_ns * reference_number_of_particles_SDS_rounded * 10 * 19

22799.999999999996

In [640]:
core_h_per_particle_ns * reference_number_of_particles_CTAB_rounded * 10 * 14

25199.999999999996

1

In [625]:
# original SDS systems without indenter
system_name_scope = list( sim_df[ 
        sim_df['indenter'].isna() & \
        (sim_df['surfactant'] == 'SDS') &
        sim_df['sf_preassembly'].isin(preassemblies_of_interest)
    ].index )

In [626]:
len(system_name_scope)

49

In [627]:
system_name_scope

['103_SDS_on_AU_111_60x35x2_bilayer_with_counterion',
 '1107_SDS_on_AU_111_51x30x2_bilayer_with_counterion',
 '1107_SDS_on_AU_111_51x30x2_cylinders_with_counterion',
 '1107_SDS_on_AU_111_51x30x2_hemicylinders_with_counterion',
 '1107_SDS_on_AU_111_51x30x2_monolayer_with_counterion',
 '123_SDS_on_AU_111_17x10x2_bilayer_with_counterion',
 '129_SDS_on_AU_111_51x30x2_bilayer_with_counterion',
 '129_SDS_on_AU_111_51x30x2_cylinders_with_counterion',
 '129_SDS_on_AU_111_51x30x2_hemicylinders_with_counterion',
 '129_SDS_on_AU_111_51x30x2_monolayer_with_counterion',
 '14_SDS_on_AU_111_17x10x2_bilayer_with_counterion',
 '1519_SDS_on_AU_111_60x35x2_bilayer_with_counterion',
 '165_SDS_on_AU_111_26x15x2_bilayer_with_counterion',
 '177_SDS_on_AU_111_60x35x2_bilayer_with_counterion',
 '19_SDS_on_AU_111_26x15x2_bilayer_with_counterion',
 '220_SDS_on_AU_111_51x30x2_bilayer_with_counterion',
 '220_SDS_on_AU_111_51x30x2_cylinders_with_counterion',
 '220_SDS_on_AU_111_51x30x2_hemicylinders_with_counterion

In [637]:
sim_df.loc[system_name_scope,'sf_nmolecules'].unique()

array([ 103, 1107,  123,  129,   14, 1519,  165,  177,   19,  220, 2214,
        246,   24,  282,  302, 3038,   33,  377,   42,  518,  564,   56,
        646,   72,   75,  887,    8,   96])