In [1]:
%load_ext autoreload
%autoreload 2

In [3]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [4]:
# matplotlib settings

# expecially for presentation, larger font settings for plotting are recommendable
SMALL_SIZE = 20
MEDIUM_SIZE = 22
BIGGER_SIZE = 26

plt.rc("font", size=MEDIUM_SIZE)          # controls default text sizes
plt.rc("axes", titlesize=MEDIUM_SIZE)     # fontsize of the axes title
plt.rc("axes", labelsize=MEDIUM_SIZE)    # fontsize of the x and y labels
plt.rc("xtick", labelsize=SMALL_SIZE)    # fontsize of the tick labels
plt.rc("ytick", labelsize=SMALL_SIZE)    # fontsize of the tick labels
plt.rc("legend", fontsize=MEDIUM_SIZE)    # legend fontsize
plt.rc("figure", titlesize=BIGGER_SIZE)  # fontsize of the figure title

plt.rcParams["figure.figsize"] = (8,5) # the standard figure size

plt.rcParams["lines.linewidth"] = 4
plt.rcParams["lines.markersize"] = 14
plt.rcParams["lines.markeredgewidth"]=1

## 1st try

In [11]:
a = np.array([ 0.45790415, -0.71493305, -0.5277788 ])

In [13]:
b = np.array([1,0,0])

In [14]:
np.cross(a,b)

array([ 0.        , -0.5277788 ,  0.71493305])

In [18]:
calpha = np.dot(a,b)/(np.linalg.norm(a)*np.linalg.norm(b))

In [19]:
calpha

0.45805168053077955

In [21]:
alpha = np.arccos(calpha)

In [22]:
alpha

1.0949941380878898

In [24]:
alpha*180/np.pi

62.738542704001354

## 2nd Try

In [26]:
a = np.array([-0.17045593, -0.75755037, 0.62502691])

In [27]:
b = np.array([0,0,1])

In [28]:
np.cross(a,b)

array([-0.75755037,  0.17045593,  0.        ])

In [29]:
calpha = np.dot(a,b)/(np.linalg.norm(a)*np.linalg.norm(b))

In [30]:
calpha

0.6270377759454986

In [31]:
alpha = np.arccos(calpha)

In [32]:
alpha

0.8930516148154538

In [33]:
alpha*180/np.pi

51.16808841626837

## 2nd try, 2nd step

In [50]:
a = np.array([30, 22, -66])

In [51]:
b = np.array([0,0,-1])

In [52]:
np.cross(a,b)

array([-22,  30,   0])

In [53]:
calpha = np.dot(a,b)/(np.linalg.norm(a)*np.linalg.norm(b))

In [54]:
calpha

0.8711400676249501

In [55]:
alpha = np.arccos(calpha)

In [56]:
alpha

0.5132769999324015

In [57]:
alpha*180/np.pi

29.408605817263247